project:
  type: book

book:
  title: "TransProRBook"
  author: "Dongyue Yu"
  favicon: TransProR_rlogo.png
  description: TransProR User Manual.
  keyword: TransProR, DL, transformer, data science, data engineering
  url: https://sssydysss.github.io/TransProRBook/
  date: "2023/10/18"
  sidebar: 
    background: "#cad4ca"
    logo: TransProR_rlogo.png
    search: true
  repo-url: https://github.com/SSSYDYSSS/TransProRBook
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  image: TransProR_rlogo.png
  comments:
    giscus:
      repo: SSSYDYSSS/TransProRBook
  open-graph:
    image: https://github.com/SSSYDYSSS/TransProRBook/blob/main/TransProR_rlogo.png
    description: R package TransProR.

  chapters:
    - index.qmd
    - Data Source and Introduction.qmd
    - summary.qmd
    - pipeline.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: false
    css: custom.css
    backgroundcolor: "#F5F5F5"

execute:
  freeze: auto




