on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # 添加设置R的步骤
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2  # 使用v2版本
        with:
          r-version: '4.3.1'  # 指定R的版本

      - name: Install rmarkdown package
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "remotes"))'

      # 使用remotes从GitHub上安装TransProR包
      - name: Install TransProR from GitHub
        run: |
          Rscript -e 'remotes::install_github("SSSYDYSSS/TransProR", build_vignettes = TRUE, auth_token = "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")'

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}